name: CI/CD Pipeline

on:
push:
branches:
- main

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2
- name: Build Docker image
run: docker build -t my-node-app .

- name: Push Docker image to Docker Hub
uses: docker/build-push-action@v2
with:
username: ${{ secrets.DOCKER_USERNAME }}
password: ${{ secrets.DOCKER_PASSWORD }}
repository: akshay2001a/my-node-app:latest
tags: latest

deploy:
runs-on: ubuntu-latest
needs: build

steps:
- name: Set up SSH
uses: webfactory/ssh-agent@v0.5.4
with:
ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

- name: SSH into EC2 and deploy
run: |
ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'docker pull akshay2001a/my-node-app:latest && docker stop my-node-app || true && docker rm my-node-app || true && docker run -d -p 80:80 --name my-node-app akshay2001a/my-node-app:latest'